### ISSUE TITLE
'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by briansloane** [singer-io/tap-bing-ads#4]
When using an ascii encoding the following error occurs. Should we explicitly set the encoding to utf-8 in the tap? There was a similar issue with the tap-fullstory as seen here: https://github.com/singer-io/tap-fullstory/pull/1

```
2018-01-02 20:38:46,083Z    tap - CRITICAL 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
2018-01-02 20:38:46,086Z    tap - Traceback (most recent call last):
2018-01-02 20:38:46,086Z    tap -   File "tap-env/bin/tap-bing-ads", line 11, in <module>
2018-01-02 20:38:46,086Z    tap -     sys.exit(main())
2018-01-02 20:38:46,086Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 696, in main
2018-01-02 20:38:46,086Z    tap -     raise exc
2018-01-02 20:38:46,086Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 693, in main
2018-01-02 20:38:46,087Z    tap -     main_impl()
2018-01-02 20:38:46,087Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 680, in main_impl
2018-01-02 20:38:46,087Z    tap -     do_sync_all_accounts(account_ids, args.catalog)
2018-01-02 20:38:46,087Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 667, in do_sync_all_accounts
2018-01-02 20:38:46,087Z    tap -     sync_account_data(account_id, catalog, selected_streams)
2018-01-02 20:38:46,087Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 655, in sync_account_data
2018-01-02 20:38:46,087Z    tap -     sync_reports(account_id, catalog)
2018-01-02 20:38:46,087Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 648, in sync_reports
2018-01-02 20:38:46,088Z    tap -     sync_report(client, account_id, report_stream)
2018-01-02 20:38:46,088Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 629, in sync_report
2018-01-02 20:38:46,088Z    tap -     report_time)
2018-01-02 20:38:46,088Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_bing_ads/__init__.py", line 558, in stream_report
2018-01-02 20:38:46,088Z    tap -     header_line = next(csv_file)[1:-1]
2018-01-02 20:38:46,088Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/encodings/ascii.py", line 26, in decode
2018-01-02 20:38:46,088Z    tap -     return codecs.ascii_decode(input, self.errors)[0]
2018-01-02 20:38:46,088Z    tap - UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
```

**Comment by awm33** [comment]
@KAllan357 Did https://github.com/singer-io/tap-bing-ads/pull/5 solve this issue?

Looking through the SDK, using `utf-8-sig` (custom Windows UTF-8 variant) might solve this, and make https://github.com/singer-io/tap-bing-ads/blob/master/tap_bing_ads/__init__.py#L599 not needed

**Comment by KAllan357** [comment]
@awm33 Yep, that solved the issue. I've actually added a line to our Dockerfile that should resolve this problem going forward:

```
root@5aa2939127a3:~# python3 -c 'import locale; print(locale.getpreferredencoding())'
ANSI_X3.4-1968
root@5aa2939127a3:~# export LANG=C.UTF-8                                                                                                                                
root@5aa2939127a3:~# python3 -c 'import locale; print(locale.getpreferredencoding())'
UTF-8
```
